export const en={
 nav:{home:'Home',about:'About Us',services:'Services',detection:'Detection Dogs',dual:'Dual-Purpose K9s',contact:'Contact',open:'Open navigation',close:'Close navigation'},
 hero:{eyebrow:'AVALA Police Dogs — Serbia, Europe',title:['Working Dogs.','Passion for Performance.'],lead:'Welcome to AVALA Police Dogs, a European provider of professionally bred, selected and trained detection and dual-purpose K9s for police, law enforcement, military and security applications.',text:'Based in Serbia, we combine practical K9 experience with a carefully developed network of breeders, trainers, working-dog professionals and veterinary specialists to identify, assess and prepare dogs for demanding operational environments.',primary:'Explore Our K9 Programs',secondary:'Contact Us',scroll:'Scroll to discover'},
 slogan:['Selected for Work.','Developed for Performance.'],
 about:{eye:'About Avala',title:'A European Supplier of High-Quality Detection and Dual-Purpose K9s',p:['Founded in 2020, AVALA Police Dogs is led by Slobodan Andjelkovich, who has more than two decades of practical experience working with police K9s. His expertise spans working-dog selection, assessment of working drives, training methodology, behavioral development and preparation for demanding operational environments.','Our approach begins with careful selection. We assess each candidate for working drive, hunt and search motivation, environmental stability, trainability, physical soundness and the ability to perform reliably under pressure.','Through our network of breeders, suppliers, trainers and veterinary professionals, we identify and develop dogs for a broad range of professional requirements while maintaining consistent selection, quality control and continuity of supply.','AVALA Police Dogs is located on the outskirts of Belgrade, Serbia, with convenient access to major European transportation routes and Belgrade International Airport.']},
 services:{eye:'What We Do',title:'Detection and Dual-Purpose K9s for Law Enforcement, Military and Security Agencies',p:'AVALA Police Dogs specializes in the selection, development and training of detection dogs and dual-purpose K9s. Our objective is to establish long-term partnerships through reliable, carefully selected working dogs and consistent supply programs.',quality:'Besides quantity we are focus on quality, as well. Every dog is individually assessed for the intended operational role.',cards:[['01','Detection Dogs','Professional detection K9 candidates selected for drive, search motivation, environmental stability and consistent operational performance.','Explore Detection Dogs'],['02','Dual-Purpose K9s','Working K9s developed for professional roles requiring detection capability combined with controlled operational engagement.','Explore Dual-Purpose K9s']]},
 detection:{eye:'Detection K9 Program',title:'Detection Dogs',p:['Our primary specialization is the development and supply of professional detection dogs.','We select candidates according to their natural working abilities and their potential to develop into reliable operational detection K9s.'],sub:'What We Look for in Detection Dog Candidates',items:['Strong working drives','High search and hunt motivation','Trainability and willingness to work','Stable and confident temperament','Environmental stability','Fast recovery from stress and distraction','Independence and persistence in search','Strong focus and concentration','Physical health and soundness','Adaptability to different operational environments'],final:'Our selection and development process is designed to identify dogs capable of maintaining reliable performance in demanding real-world conditions.'},
 gsp:{eye:'Our Primary Detection Breed',title:'German Shorthaired Pointer',p:['The German Shorthaired Pointer is the cornerstone of our detection dog program, representing more than 95% of the detection dogs we supply to the market.','Its combination of high working drive, strong hunt motivation, athleticism, endurance, trainability and adaptability makes it particularly well suited to demanding detection work.','While the GSP is our primary breed, we also work with selected Labrador Retrievers and English Springer Spaniels, depending on the specific requirements of the customer and operational role.'],stat:'of our detection K9 program'},
 dual:{eye:'Dual-Purpose Program',title:'Dual-Purpose K9s',p:['Our dual-purpose K9s are selected and developed for roles combining detection capability with controlled operational engagement.','In addition to the qualities required for a professional detection dog, candidates must demonstrate the confidence, stability and physical and behavioral characteristics necessary for controlled bite work and operational deployment.'],sub:'A Dual-Purpose K9 Candidate Should Demonstrate',items:['Courage and confidence','Stability under pressure','Controlled aggression and engagement','No handler-directed aggression','Strong nerve and environmental stability','Clear on/off switch','Strong and calm grip','Trainability and handler responsiveness','Physical soundness and endurance'],final:"The final selection is based on the individual dog's suitability for the intended operational role, with emphasis on reliability, controllability and consistent performance."},
 process:{eye:'Our Method',title:'Selection Process',steps:[['Candidate Identification','Selection through our professional network of breeders, suppliers and working-dog specialists.'],['Working Assessment','Evaluation of drive, temperament, search motivation, environmental stability and trainability.'],['Health & Soundness','Physical suitability and veterinary assessment for professional working requirements.'],['Development','Structured development and preparation according to the intended operational role.'],['Operational Suitability','Final assessment with emphasis on reliability and consistent performance.']]},
 cta:{text:'Partner with AVALA Police Dogs for professional detection and dual-purpose K9 requirements.',button:'Contact AVALA Police Dogs',call:'Call +381 64 185 5765'},
 contact:{eye:'Direct Inquiry',title:'Contact AVALA Police Dogs',intro:'For information about available dogs, supply programs or professional K9 requirements, contact us directly.',name:'Name',org:'Organization',country:'Country',email:'Email',phone:'Phone',interest:'Interested In',options:['Detection Dogs','Dual-Purpose K9s','Other'],message:'Message',send:'Send Inquiry',success:'Thank you. Your inquiry is ready to be connected to our email service.',location:'Ralja, Belgrade, Serbia',map:'Strategic location near Belgrade and major European transport routes.',openMap:'Open in Google Maps'},
 footer:{rights:'© 2026 AVALA Police Dogs. All rights reserved.',region:'Serbia, Europe'}
} as const
