import type { Copy } from './types'
export const sr:Copy={
 nav:{home:'Početna',about:'O nama',services:'Usluge',detection:'Psi za detekciju',dual:'Višenamenski K9',contact:'Kontakt',open:'Otvori navigaciju',close:'Zatvori navigaciju'},
 hero:{eyebrow:'AVALA Police Dogs — Srbija, Evropa',title:['Radni psi.','Strast prema vrhunskim performansama.'],lead:'Dobro došli u AVALA Police Dogs, evropsku kompaniju za profesionalni uzgoj, selekciju i obuku pasa za detekciju i višenamenskih K9 pasa za policiju, vojsku, službe za sprovođenje zakona i sektor bezbednosti.',text:'Sa sedištem u Srbiji, spajamo praktično K9 iskustvo sa pažljivo razvijenom mrežom odgajivača, trenera, stručnjaka za radne pse i veterinara kako bismo prepoznali, procenili i pripremili pse za zahtevna operativna okruženja.',primary:'Istražite naše K9 programe',secondary:'Kontaktirajte nas',scroll:'Skrolujte za više'},
 slogan:['Odabrani za rad.','Razvijeni za vrhunske performanse.'],brandSub:'Profesionalna selekcija i razvoj radnih K9 pasa iz Srbije za operativne timove širom Evrope i sveta.',
 about:{eye:'O kompaniji Avala',title:'Evropski dobavljač vrhunskih pasa za detekciju i višenamenskih K9 pasa',p:['Osnovana 2020. godine, AVALA Police Dogs je pod vođstvom Slobodana Anđelkovića, sa više od dve decenije praktičnog iskustva u radu sa policijskim K9 psima. Njegova stručnost obuhvata selekciju, procenu radnih nagona, metodologiju obuke, razvoj ponašanja i pripremu za zahtevna operativna okruženja.','Naš pristup počinje pažljivom selekcijom. Svakog kandidata procenjujemo prema radnom nagonu, motivaciji za lov i pretragu, stabilnosti u okruženju, sposobnosti učenja, fizičkom zdravlju i pouzdanosti pod pritiskom.','Kroz mrežu odgajivača, dobavljača, trenera i veterinara pronalazimo i razvijamo pse za širok spektar profesionalnih zahteva, uz doslednu selekciju, kontrolu kvaliteta i kontinuitet isporuke.','AVALA Police Dogs se nalazi na obodu Beograda, uz dobru povezanost sa glavnim evropskim transportnim pravcima i Aerodromom Nikola Tesla.'],stats:[['2020','Godina osnivanja'],['20+ godina','Praktičnog K9 iskustva'],['Srbija','Strateška evropska lokacija'],['Međunarodno','Profesionalno snabdevanje K9 psima']]},
 services:{eye:'Čime se bavimo',title:'Psi za detekciju i višenamenski K9 psi za policijske, vojne i bezbednosne službe',p:'AVALA Police Dogs je specijalizovana za selekciju, razvoj i obuku pasa za detekciju i višenamenskih K9 pasa za profesionalnu operativnu upotrebu. Cilj nam je dugoročno partnerstvo kroz pouzdane, pažljivo odabrane radne pse i stabilne programe snabdevanja. Uz količinu, ključan nam je kvalitet. Svaki pas se procenjuje pojedinačno za namenjenu operativnu ulogu.',cards:[['01','Psi za detekciju','Profesionalni K9 kandidati birani prema nagonu, motivaciji za pretragu, stabilnosti u okruženju i doslednim operativnim performansama.','Istražite pse za detekciju'],['02','Višenamenski K9 psi','Radni K9 psi razvijeni za profesionalne uloge koje spajaju detekciju sa kontrolisanim operativnim angažovanjem.','Istražite višenamenske K9 pse']]},
 detection:{eye:'Program pasa za detekciju',title:'Psi za detekciju',p:['Naša primarna specijalnost je razvoj i snabdevanje profesionalnim psima za detekciju.','Kandidate biramo prema njihovim prirodnim radnim sposobnostima i potencijalu da postanu pouzdani operativni K9 psi za detekciju.'],sub:'Osobine koje tražimo kod kandidata',items:['Izraženi radni nagoni','Visoka motivacija za pretragu i lov','Sposobnost učenja i volja za rad','Stabilan i samouveren temperament','Stabilnost u različitim okruženjima','Brz oporavak od stresa i ometanja','Samostalnost i istrajnost u pretrazi','Snažan fokus i koncentracija','Fizičko zdravlje i pravilna građa','Prilagodljivost različitim operativnim okruženjima'],final:'Naš proces selekcije i razvoja osmišljen je da prepozna pse sposobne za pouzdan rad u zahtevnim realnim uslovima.'},
 gsp:{eye:'Naša primarna rasa za detekciju',title:'Nemački kratkodlaki ptičar',p:['Nemački kratkodlaki ptičar je temelj našeg programa pasa za detekciju i čini više od 95% pasa za detekciju koje isporučujemo tržištu.','Spoj snažnog radnog nagona, motivacije za lov, atletskih sposobnosti, izdržljivosti, sposobnosti učenja i prilagodljivosti čini ovu rasu naročito pogodnom za zahtevan detekcijski rad.','Iako je nemački kratkodlaki ptičar naša primarna rasa, radimo i sa odabranim labrador retriverima i engleskim špringer španijelima, u zavisnosti od zahteva kupca i operativne uloge.'],stat:'našeg programa K9 pasa za detekciju'},
 dual:{eye:'Višenamenski program',title:'Višenamenski K9 psi',p:['Naši višenamenski K9 psi biraju se i razvijaju za uloge koje spajaju sposobnost detekcije sa kontrolisanim operativnim angažovanjem.','Pored kvaliteta potrebnih profesionalnom psu za detekciju, kandidati moraju pokazati samopouzdanje, stabilnost i fizičke i bihevioralne osobine potrebne za kontrolisan zaštitni rad i operativno angažovanje.'],sub:'Kandidat za višenamenskog K9 psa treba da pokaže',items:['Hrabrost i samopouzdanje','Stabilnost pod pritiskom','Kontrolisanu agresiju i angažovanje','Bez agresije prema vodiču','Čvrste nerve i stabilnost u okruženju','Jasan prelaz između rada i mirovanja','Snažan i miran ugriz','Sposobnost učenja i odziv prema vodiču','Fizičko zdravlje i izdržljivost'],final:'Konačna selekcija zasniva se na pogodnosti svakog psa za namenjenu operativnu ulogu, sa naglaskom na pouzdanost, kontrolu i dosledne performanse.'},
 process:{eye:'Naš metod',title:'Proces selekcije',steps:[['Prepoznavanje kandidata','Selekcija kroz profesionalnu mrežu odgajivača, dobavljača i stručnjaka za radne pse.'],['Radna procena','Procena nagona, temperamenta, motivacije za pretragu, stabilnosti u okruženju i sposobnosti učenja.'],['Zdravlje i fizička spremnost','Veterinarska procena i provera fizičke pogodnosti za profesionalne radne zahteve.'],['Razvoj','Strukturisan razvoj i priprema u skladu sa namenjenom operativnom ulogom.'],['Operativna pogodnost','Konačna procena sa naglaskom na pouzdanost i dosledne performanse.']]},
 gallery:{eye:'Na terenu',title:'Svrha u svakom pokretu.',labels:['Obuka za detekciju','Nemački kratkodlaki ptičar','Vodič i K9','Operativni razvoj']},
 cta:{text:'Postanite partner kompanije AVALA Police Dogs za profesionalne potrebe pasa za detekciju i višenamenskih K9 pasa.',button:'Kontaktirajte AVALA Police Dogs',call:'Pozovite +381 64 185 5765'},
 contact:{eye:'Direktan upit',title:'Kontaktirajte AVALA Police Dogs',intro:'Za informacije o dostupnim psima, programima snabdevanja ili profesionalnim K9 potrebama, obratite nam se direktno.',name:'Ime',org:'Organizacija',country:'Država',email:'Email',phone:'Telefon',interest:'Oblast interesovanja',options:['Psi za detekciju','Višenamenski K9 psi','Drugo'],message:'Poruka',send:'Pošaljite upit',success:'Hvala. Vaš upit je spreman za povezivanje sa email servisom.',location:'Ralja, Beograd, Srbija',map:'Strateška lokacija blizu Beograda i glavnih evropskih transportnih pravaca.',openMap:'Otvori u Google mapama'},
 footer:{rights:'© 2026 AVALA Police Dogs. Sva prava zadržana.',region:'Srbija, Evropa'}
}
